# This is a better name.
[config]
additional_profiles = ["release"]

# ----------------------------
# Setup environment variables.
# ----------------------------

[env]
PROJECT_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}"

[env.development]
TARGET_DIR = "target/debug"

[env.release]
TARGET_DIR = "target/release"

# ------------------------
# This cleans the project.
# ------------------------

[tasks.clean]
clear = true
workspace = false
dependencies = [
    "cargo-clean",
    "remove-artifacts"
]

[tasks.cargo-clean]
private = true
workspace = false
script = '''
    cargo clean
'''

[tasks.remove-artifacts]
private = true
workspace = false
script = '''
    rm -rf artifacts
'''

# ------------------------
# This builds the project.
# ------------------------

# Builds the project.
[tasks.build]
clear = true
workspace = false
dependencies = [
    "build-debug",
    "build-release",
    "build-macos-app"
]

[tasks.build-debug]
clear = true
private = true
workspace = false
condition = { profiles = ["development"] }
script = '''
    cargo build
'''

[tasks.build-release]
clear = true
private = true
workspace = false
condition = { profiles = ["release"] }
script = '''
    cargo build --release
'''

[tasks.build-macos-app]
private = true
workspace = false
condition = { platforms = ["mac"] }
script = '''
    echo ${PROJECT_DIR}
    echo ${TARGET_DIR}
'''

# ----------------------
# This runs the project.
# ----------------------

# Builds the project.
[tasks.run]
clear = true
workspace = false
dependencies = [
    "run-debug",
    "run-release"
]

[tasks.run-debug]
clear = true
private = true
workspace = false
condition = { profiles = ["development"] }
script = '''
    cargo run
'''

[tasks.run-release]
clear = true
private = true
workspace = false
condition = { profiles = ["release"] }
script = '''
    cargo run --release
'''
