# This is a better name.
[config]
additional_profiles = ["release"]

# ----------------------------
# Setup environment variables.
# ----------------------------

[env]
PROJECT_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}"
ARTIFACTS_DIR = "${PROJECT_DIR}/artifacts"
APP_NAME = "cef-ui-simple"
APP_HELPER_NAME = "cef-ui-simple-helper"

[env.development]
TARGET_DIR = "target/debug"

[env.release]
TARGET_DIR = "target/release"

# ------------------------
# This cleans the project.
# ------------------------

[tasks.clean]
clear = true
workspace = false
dependencies = [
    "cargo-clean",
    "remove-artifacts"
]

[tasks.cargo-clean]
private = true
workspace = false
script = '''
    cargo clean
'''

[tasks.remove-artifacts]
private = true
workspace = false
script = '''
    rm -rf artifacts
'''

# ------------------------
# This builds the project.
# ------------------------

# Builds the project.
[tasks.build]
clear = true
workspace = false
dependencies = [
    "build-debug",
    "build-release",
    "build-macos-debug-helper",
    "build-macos-release-helper",
    "build-macos-app"
]

[tasks.build-debug]
clear = true
private = true
workspace = false
condition = { profiles = ["development"] }
script = '''
    cargo build --bin ${APP_NAME}
'''

[tasks.build-release]
clear = true
private = true
workspace = false
condition = { profiles = ["release"] }
script = '''
    cargo build --release --bin ${APP_NAME}
'''

[tasks.build-macos-debug-helper]
clear = true
private = true
workspace = false
condition = { profiles = ["development"], platforms = ["mac"] }
script = '''
    cargo build --bin ${APP_HELPER_NAME}
'''

[tasks.build-macos-release-helper]
clear = true
private = true
workspace = false
condition = { profiles = ["release"], platforms = ["mac"] }
script = '''
    cargo build --release --bin ${APP_HELPER_NAME}
'''

[tasks.build-macos-app]
private = true
workspace = false
condition = { platforms = ["mac"] }
env = { "RES_DIR" = "resources/macos" }
script = '''
    # The path to the app.
    APP_DIR="${TARGET_DIR}/${APP_NAME}.app"

    # Remove any existing app.
    rm -fr "${APP_DIR}"

    # Setup the main app.
    mkdir -p "${APP_DIR}/Contents/Frameworks"
    mkdir -p "${APP_DIR}/Contents/MacOS"
    mkdir -p "${APP_DIR}/Contents/Resources"
    cp -r "${RES_DIR}/Info.plist" "${APP_DIR}/Contents"
    cp -r "${RES_DIR}/Icon.icns" "${APP_DIR}/Contents/Resources"
    cp -r "${RES_DIR}/English.lproj" "${APP_DIR}/Contents/Resources/English.lproj"
    cp "${TARGET_DIR}/${APP_NAME}" "${APP_DIR}/Contents/MacOS"

    # Copy the CEF framework.
    cp -r "${ARTIFACTS_DIR}/cef/Chromium Embedded Framework.framework" "${APP_DIR}/Contents/Frameworks"

    # Create the helper app.
    HELPER_NAME="${APP_NAME} Helper"
    HELPER_DIR="${APP_DIR}/Contents/Frameworks/${HELPER_NAME}.app"
    HELPER_PLIST="HelperInfo.plist"
    mkdir -p "${HELPER_DIR}/Contents/MacOS"
    cp -r "${RES_DIR}/${HELPER_PLIST}" "${HELPER_DIR}/Contents/Info.plist"
    cp "${TARGET_DIR}/${APP_HELPER_NAME}" "${HELPER_DIR}/Contents/MacOS/${HELPER_NAME}"

    # Create the alerts app.
    HELPER_NAME="${APP_NAME} Helper (Alerts)"
    HELPER_DIR="${APP_DIR}/Contents/Frameworks/${HELPER_NAME}.app"
    HELPER_PLIST="AlertsHelperInfo.plist"
    mkdir -p "${HELPER_DIR}/Contents/MacOS"
    cp -r "${RES_DIR}/${HELPER_PLIST}" "${HELPER_DIR}/Contents/Info.plist"
    cp "${TARGET_DIR}/${APP_HELPER_NAME}" "${HELPER_DIR}/Contents/MacOS/${HELPER_NAME}"

    # Create the gpu app.
    HELPER_NAME="${APP_NAME} Helper (GPU)"
    HELPER_DIR="${APP_DIR}/Contents/Frameworks/${HELPER_NAME}.app"
    HELPER_PLIST="GpuHelperInfo.plist"
    mkdir -p "${HELPER_DIR}/Contents/MacOS"
    cp -r "${RES_DIR}/${HELPER_PLIST}" "${HELPER_DIR}/Contents/Info.plist"
    cp "${TARGET_DIR}/${APP_HELPER_NAME}" "${HELPER_DIR}/Contents/MacOS/${HELPER_NAME}"

    # Create the plugin app.
    HELPER_NAME="${APP_NAME} Helper (Plugin)"
    HELPER_DIR="${APP_DIR}/Contents/Frameworks/${HELPER_NAME}.app"
    HELPER_PLIST="PluginHelperInfo.plist"
    mkdir -p "${HELPER_DIR}/Contents/MacOS"
    cp -r "${RES_DIR}/${HELPER_PLIST}" "${HELPER_DIR}/Contents/Info.plist"
    cp "${TARGET_DIR}/${APP_HELPER_NAME}" "${HELPER_DIR}/Contents/MacOS/${HELPER_NAME}"

    # Create the renderer app.
    HELPER_NAME="${APP_NAME} Helper (Renderer)"
    HELPER_DIR="${APP_DIR}/Contents/Frameworks/${HELPER_NAME}.app"
    HELPER_PLIST="RendererHelperInfo.plist"
    mkdir -p "${HELPER_DIR}/Contents/MacOS"
    cp -r "${RES_DIR}/${HELPER_PLIST}" "${HELPER_DIR}/Contents/Info.plist"
    cp "${TARGET_DIR}/${APP_HELPER_NAME}" "${HELPER_DIR}/Contents/MacOS/${HELPER_NAME}"
'''

# ----------------------
# This runs the project.
# ----------------------

# Builds the project.
[tasks.run]
clear = true
workspace = false
dependencies = [
    "run-debug",
    "run-release"
]

[tasks.run-debug]
clear = true
private = true
workspace = false
condition = { profiles = ["development"] }
script = '''
    cargo run --bin ${APP_NAME}
'''

[tasks.run-release]
clear = true
private = true
workspace = false
condition = { profiles = ["release"] }
script = '''
    cargo run --release --bin ${APP_NAME}
'''
