version = "Two"
edition = "2021"
newline_style = "Unix"
trailing_comma = "Never"
merge_derives = false
struct_field_align_threshold = 32
chain_width = 40
imports_granularity = "Crate"
match_block_trailing_comma = true
