[package]
name = "cef-ui-helper"
version = "0.1.0"
edition = "2021"

[features]
sandbox = []
default = ["sandbox"]

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-log = { workspace = true }
tracing-subscriber = { workspace = true }
libloading = "0.8"
