[package]
name = "cef-ui"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
cef-ui-util = { path = "../cef-ui-util" }
anyhow = { workspace = true }
tracing-log = { workspace = true }
paste = "1.0"
dunce = "1.0"
parking_lot = "0.12"
bitflags = "2.4"
chrono = "0.4"
